baseURL = 'https://strawberryoolongtea.github.io/'
languageCode = 'en-us'
title = "Strawberry ウーロン茶"
theme = "hugo-theme-tokiwa"

disqusShortname = "strawberryoolongtea"

[params]
description = """
☪︎ Der Vogel kämpft sich aus dem Ei ✦
"""
math = true # for introducing $KaTEX$
env = "production" # for Google Analytics and DISQUS.
useChineseFonts = true # for font Noto Serif etc.
bannerFont = "fonts/exampleFont" # custom your own font for the title.
postDateFormat = "2006-1-2" # override custom date format posts.

[menu]
# Shown in the side menu.
  [[menu.main]]
    name = "About"
    weight = 1
    url = "/about/"
  [[menu.main]]
    name = "Projects"
    weight = 2
    url = "/projects/"
  [[menu.main]]
    name = "Posts"
    weight = 3
    url = "/posts/"
  [[menu.main]]
    name = "Categories"
    weight = 4
    identifier = "post"
    url = "/categories/"
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 5

[social]
github="http://github.com/strawberryoolongtea"

[taxonomies]
   tag = "tags"
   category = "categories"

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    style = "monokai"
